# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulationUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 546)
        self.centralLayout = QtWidgets.QWidget(MainWindow)
        self.centralLayout.setObjectName("centralLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralLayout)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 30, 391, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertLayout.setContentsMargins(0, 0, 0, 0)
        self.vertLayout.setObjectName("vertLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.meatThicknessTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.meatThicknessTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.meatThicknessTitle.setObjectName("meatThicknessTitle")
        self.gridLayout.addWidget(self.meatThicknessTitle, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ovenTempLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ovenTempLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ovenTempLabel.setObjectName("ovenTempLabel")
        self.horizontalLayout.addWidget(self.ovenTempLabel)
        self.tempUnit = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tempUnit.setObjectName("tempUnit")
        self.horizontalLayout.addWidget(self.tempUnit)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.ovenTempTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ovenTempTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.ovenTempTitle.setObjectName("ovenTempTitle")
        self.gridLayout.addWidget(self.ovenTempTitle, 0, 0, 1, 1)
        self.meatSelector = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.meatSelector.setObjectName("meatSelector")
        self.meatSelector.addItem("")
        self.meatSelector.addItem("")
        self.meatSelector.addItem("")
        self.meatSelector.addItem("")
        self.meatSelector.addItem("")
        self.gridLayout.addWidget(self.meatSelector, 1, 2, 1, 1)
        self.ovenTempSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.ovenTempSlider.setAutoFillBackground(False)
        self.ovenTempSlider.setMinimum(200)
        self.ovenTempSlider.setMaximum(500)
        self.ovenTempSlider.setSingleStep(1)
        self.ovenTempSlider.setSliderPosition(350)
        self.ovenTempSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ovenTempSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.ovenTempSlider.setTickInterval(50)
        self.ovenTempSlider.setObjectName("ovenTempSlider")
        self.gridLayout.addWidget(self.ovenTempSlider, 1, 0, 1, 1)
        self.meatThicknessSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.meatThicknessSlider.setAutoFillBackground(False)
        self.meatThicknessSlider.setMinimum(1)
        self.meatThicknessSlider.setMaximum(20)
        self.meatThicknessSlider.setSingleStep(1)
        self.meatThicknessSlider.setPageStep(1)
        self.meatThicknessSlider.setSliderPosition(5)
        self.meatThicknessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.meatThicknessSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.meatThicknessSlider.setTickInterval(2)
        self.meatThicknessSlider.setObjectName("meatThicknessSlider")
        self.gridLayout.addWidget(self.meatThicknessSlider, 4, 0, 1, 1)
        self.meatLengthSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.meatLengthSlider.setAutoFillBackground(False)
        self.meatLengthSlider.setMinimum(1)
        self.meatLengthSlider.setMaximum(50)
        self.meatLengthSlider.setSingleStep(1)
        self.meatLengthSlider.setPageStep(1)
        self.meatLengthSlider.setSliderPosition(5)
        self.meatLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.meatLengthSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.meatLengthSlider.setTickInterval(5)
        self.meatLengthSlider.setObjectName("meatLengthSlider")
        self.gridLayout.addWidget(self.meatLengthSlider, 4, 2, 1, 1)
        self.meatSelectTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.meatSelectTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.meatSelectTitle.setObjectName("meatSelectTitle")
        self.gridLayout.addWidget(self.meatSelectTitle, 0, 2, 1, 1)
        self.meatLengthTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.meatLengthTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.meatLengthTitle.setObjectName("meatLengthTitle")
        self.gridLayout.addWidget(self.meatLengthTitle, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.meatThicknessLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.meatThicknessLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meatThicknessLabel.setObjectName("meatThicknessLabel")
        self.horizontalLayout_2.addWidget(self.meatThicknessLabel)
        self.thickUnitLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.thickUnitLabel.setObjectName("thickUnitLabel")
        self.horizontalLayout_2.addWidget(self.thickUnitLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.meatLengthLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.meatLengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meatLengthLabel.setObjectName("meatLengthLabel")
        self.horizontalLayout_3.addWidget(self.meatLengthLabel)
        self.lengthUnitLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lengthUnitLabel.setObjectName("lengthUnitLabel")
        self.horizontalLayout_3.addWidget(self.lengthUnitLabel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 2, 1, 1)
        self.vertLayout.addLayout(self.gridLayout)
        self.calculateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calculateButton.setObjectName("calculateButton")
        self.vertLayout.addWidget(self.calculateButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralLayout)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 441, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setWordWrap(True)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.Byline = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Byline.setObjectName("Byline")
        self.verticalLayout.addWidget(self.Byline)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.timeToCookLabel = QtWidgets.QLabel(self.centralLayout)
        self.timeToCookLabel.setGeometry(QtCore.QRect(610, 410, 221, 79))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeToCookLabel.setFont(font)
        self.timeToCookLabel.setText("")
        self.timeToCookLabel.setObjectName("timeToCookLabel")
        self.timeToCookTitle = QtWidgets.QLabel(self.centralLayout)
        self.timeToCookTitle.setGeometry(QtCore.QRect(490, 320, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeToCookTitle.setFont(font)
        self.timeToCookTitle.setObjectName("timeToCookTitle")
        MainWindow.setCentralWidget(self.centralLayout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.ovenTempSlider.valueChanged['int'].connect(self.ovenTempLabel.setNum)
        self.meatThicknessSlider.valueChanged['int'].connect(self.meatThicknessLabel.setNum)
        self.meatLengthSlider.valueChanged['int'].connect(self.meatLengthLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Heat Conduction in Food"))
        self.meatThicknessTitle.setText(_translate("MainWindow", "Meat Thickness (cm)"))
        self.ovenTempLabel.setText(_translate("MainWindow", "350"))
        self.tempUnit.setText(_translate("MainWindow", "F"))
        self.ovenTempTitle.setText(_translate("MainWindow", "Oven Temperature (F)"))
        self.meatSelector.setCurrentText(_translate("MainWindow", "Chicken"))
        self.meatSelector.setItemText(0, _translate("MainWindow", "Chicken"))
        self.meatSelector.setItemText(1, _translate("MainWindow", "Salmon"))
        self.meatSelector.setItemText(2, _translate("MainWindow", "Beef (Lean)"))
        self.meatSelector.setItemText(3, _translate("MainWindow", "Pork (Lean)"))
        self.meatSelector.setItemText(4, _translate("MainWindow", "Veal"))
        self.meatSelectTitle.setText(_translate("MainWindow", "Type of Meat"))
        self.meatLengthTitle.setText(_translate("MainWindow", "Meat Length (cm)"))
        self.meatThicknessLabel.setText(_translate("MainWindow", "5"))
        self.thickUnitLabel.setText(_translate("MainWindow", "cm"))
        self.meatLengthLabel.setText(_translate("MainWindow", "5"))
        self.lengthUnitLabel.setText(_translate("MainWindow", "cm"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate!"))
        self.Title.setText(_translate("MainWindow", "How long does it take for meat to become safe for eating?"))
        self.Byline.setText(_translate("MainWindow", "A simulation by Zong Lam for CHME 3312"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Introduction: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">- This program tells you how long it takes to cook a piece of meat to safe temperatures with only heat conduction</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">- Simulates certain kilns that cover meat entirely</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">- Assumptions:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    2D Heat Flow</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    Not at Steady-State</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    Constant Properties</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    \'Walls\' or surface of meat is at the temperature of kiln/oven</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    No Generation</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">Instructions:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">- Use the sliders to play around with the temperature and the dimensions of the piece of meat</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">- Use the dropdown menu to choose the type of meat to test</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">- Click on calculate when ready! </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">-The time for the center of the meat to be at safe, USDA recommended temperatures will be displayed</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">Known Bugs and Issues:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">- Calculations can take a while depending on how strong your computer is, especially for large pieces of meat at low temperatures</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">- Program may crash with an overflow error at times (unreproducable)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#000000;\"><br /></p></body></html>"))
        self.timeToCookTitle.setText(_translate("MainWindow", "Time to cook:"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

